    /**
     * Enables or disables touch events for the confetti generated by this manager. By enabling
     * touch, the user can touch individual confetto and drag/fling them on the screen independent
     * of their original animation state.
     *
     * @param touchEnabled whether or not to enable touch.
     * @return the confetti manager so that the set calls can be chained.
     */
    public ConfettiManager setTouchEnabled(boolean touchEnabled) {
        this.confettiView.setTouchEnabled(touchEnabled);
        return this;
    }

