    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.cityId);
        dest.writeString(this.cityName);
        dest.writeString(this.dataUpdateTime);
        dest.writeString(this.airQulityIndex);
        dest.writeString(this.pm25);
        dest.writeString(this.pm10);
        dest.writeString(this.so2);
        dest.writeString(this.no2);
        dest.writeString(this.co);
        dest.writeString(this.o3);
        dest.writeString(this.airQulityType);
        dest.writeString(this.weatherCode);
        dest.writeString(this.weatherDescription);
        dest.writeString(this.currentTemperature);
        dest.writeString(this.feltTemperature);
        dest.writeString(this.rainfall);
        dest.writeString(this.humidity);
        dest.writeString(this.airPressure);
        dest.writeString(this.visibility);
        dest.writeString(this.windSpeed);
        dest.writeString(this.windScale);
        dest.writeString(this.windDirection);
        dest.writeString(this.dressBrief);
        dest.writeString(this.dressDescription);
        dest.writeString(this.uvBrief);
        dest.writeString(this.uvDescription);
        dest.writeString(this.carWashBrief);
        dest.writeString(this.carWashDescription);
        dest.writeString(this.travelBrief);
        dest.writeString(this.travelDescription);
        dest.writeString(this.fluBrief);
        dest.writeString(this.fluDescription);
        dest.writeString(this.sportBrief);
        dest.writeString(this.sportDescription);
        dest.writeTypedList(this.forecasts);
    }

