    public static WeatherForecastDbHelper.WeatherForecastRecord updateWeatherForecast(
            Context context,
            long locationId,
            Integer widgetId,
            RemoteViews remoteViews,
            Integer forecast_1_widget_day_layout,
            int forecast_1_widget_icon,
            int forecast_1_widget_day,
            int forecast_1_widget_temperatures,
            Integer forecast_2_widget_day_layout,
            int forecast_2_widget_icon,
            int forecast_2_widget_day,
            int forecast_2_widget_temperatures,
            Integer forecast_3_widget_day_layout,
            int forecast_3_widget_icon,
            int forecast_3_widget_day,
            int forecast_3_widget_temperatures,
            Integer forecast_4_widget_day_layout,
            int forecast_4_widget_icon,
            int forecast_4_widget_day,
            int forecast_4_widget_temperatures,
            Integer forecast_5_widget_day_layout,
            int forecast_5_widget_icon,
            int forecast_5_widget_day,
            int forecast_5_widget_temperatures) {
        return updateWeatherForecast(
                context,
                locationId,
                AppPreference.getTextColor(context),
                widgetId,
                remoteViews,
                forecast_1_widget_day_layout,
                forecast_1_widget_icon,
                forecast_1_widget_day,
                forecast_1_widget_temperatures,
                forecast_2_widget_day_layout,
                forecast_2_widget_icon,
                forecast_2_widget_day,
                forecast_2_widget_temperatures,
                forecast_3_widget_day_layout,
                forecast_3_widget_icon,
                forecast_3_widget_day,
                forecast_3_widget_temperatures,
                forecast_4_widget_day_layout,
                forecast_4_widget_icon,
                forecast_4_widget_day,
                forecast_4_widget_temperatures,
                forecast_5_widget_day_layout,
                forecast_5_widget_icon,
                forecast_5_widget_day,
                forecast_5_widget_temperatures);
    }

